package com.iamlile.jira.burndown.model;

public class JiraWithBLOBs extends Jira {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jira.board_watch
     *
     * @mbg.generated Sun Mar 11 14:31:36 CST 2018
     */
    private String boardWatch;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jira.board_watch
     *
     * @return the value of jira.board_watch
     *
     * @mbg.generated Sun Mar 11 14:31:36 CST 2018
     */
    public String getBoardWatch() {
        return boardWatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jira.board_watch
     *
     * @param boardWatch the value for jira.board_watch
     *
     * @mbg.generated Sun Mar 11 14:31:36 CST 2018
     */
    public void setBoardWatch(String boardWatch) {
        this.boardWatch = boardWatch == null ? null : boardWatch.trim();
    }
}