package com.iamlile.jira.burndown.model;

public class JiraKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jira.id
     *
     * @mbg.generated Sun Mar 11 14:31:36 CST 2018
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jira.id
     *
     * @return the value of jira.id
     *
     * @mbg.generated Sun Mar 11 14:31:36 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jira.id
     *
     * @param id the value for jira.id
     *
     * @mbg.generated Sun Mar 11 14:31:36 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }
}