package com.iamlile.jira.burndown.model;

public class Jira extends JiraKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jira.name
     *
     * @mbg.generated Sun Mar 11 13:57:37 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jira.url
     *
     * @mbg.generated Sun Mar 11 13:57:37 CST 2018
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jira.username
     *
     * @mbg.generated Sun Mar 11 13:57:37 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jira.password
     *
     * @mbg.generated Sun Mar 11 13:57:37 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jira.task_percent_id
     *
     * @mbg.generated Sun Mar 11 13:57:37 CST 2018
     */
    private String taskPercentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jira.name
     *
     * @return the value of jira.name
     *
     * @mbg.generated Sun Mar 11 13:57:37 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jira.name
     *
     * @param name the value for jira.name
     *
     * @mbg.generated Sun Mar 11 13:57:37 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jira.url
     *
     * @return the value of jira.url
     *
     * @mbg.generated Sun Mar 11 13:57:37 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jira.url
     *
     * @param url the value for jira.url
     *
     * @mbg.generated Sun Mar 11 13:57:37 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jira.username
     *
     * @return the value of jira.username
     *
     * @mbg.generated Sun Mar 11 13:57:37 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jira.username
     *
     * @param username the value for jira.username
     *
     * @mbg.generated Sun Mar 11 13:57:37 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jira.password
     *
     * @return the value of jira.password
     *
     * @mbg.generated Sun Mar 11 13:57:37 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jira.password
     *
     * @param password the value for jira.password
     *
     * @mbg.generated Sun Mar 11 13:57:37 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jira.task_percent_id
     *
     * @return the value of jira.task_percent_id
     *
     * @mbg.generated Sun Mar 11 13:57:37 CST 2018
     */
    public String getTaskPercentId() {
        return taskPercentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jira.task_percent_id
     *
     * @param taskPercentId the value for jira.task_percent_id
     *
     * @mbg.generated Sun Mar 11 13:57:37 CST 2018
     */
    public void setTaskPercentId(String taskPercentId) {
        this.taskPercentId = taskPercentId == null ? null : taskPercentId.trim();
    }
}