package com.iamlile.jira.burndown.model;

public class JiraSprintWithBLOBs extends JiraSprint {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jira_sprint.working_day_plan
     *
     * @mbg.generated Sun Mar 11 13:57:37 CST 2018
     */
    private String workingDayPlan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jira_sprint.cross_ver_issues
     *
     * @mbg.generated Sun Mar 11 13:57:37 CST 2018
     */
    private String crossVerIssues;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jira_sprint.issues
     *
     * @mbg.generated Sun Mar 11 13:57:37 CST 2018
     */
    private String issues;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jira_sprint.working_day_plan
     *
     * @return the value of jira_sprint.working_day_plan
     *
     * @mbg.generated Sun Mar 11 13:57:37 CST 2018
     */
    public String getWorkingDayPlan() {
        return workingDayPlan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jira_sprint.working_day_plan
     *
     * @param workingDayPlan the value for jira_sprint.working_day_plan
     *
     * @mbg.generated Sun Mar 11 13:57:37 CST 2018
     */
    public void setWorkingDayPlan(String workingDayPlan) {
        this.workingDayPlan = workingDayPlan == null ? null : workingDayPlan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jira_sprint.cross_ver_issues
     *
     * @return the value of jira_sprint.cross_ver_issues
     *
     * @mbg.generated Sun Mar 11 13:57:37 CST 2018
     */
    public String getCrossVerIssues() {
        return crossVerIssues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jira_sprint.cross_ver_issues
     *
     * @param crossVerIssues the value for jira_sprint.cross_ver_issues
     *
     * @mbg.generated Sun Mar 11 13:57:37 CST 2018
     */
    public void setCrossVerIssues(String crossVerIssues) {
        this.crossVerIssues = crossVerIssues == null ? null : crossVerIssues.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jira_sprint.issues
     *
     * @return the value of jira_sprint.issues
     *
     * @mbg.generated Sun Mar 11 13:57:37 CST 2018
     */
    public String getIssues() {
        return issues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jira_sprint.issues
     *
     * @param issues the value for jira_sprint.issues
     *
     * @mbg.generated Sun Mar 11 13:57:37 CST 2018
     */
    public void setIssues(String issues) {
        this.issues = issues == null ? null : issues.trim();
    }
}