package com.iamlile.jira.burndown.model;

public class JiraSprint extends JiraSprintKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jira_sprint.board_id
     *
     * @mbg.generated Sun Mar 11 14:31:36 CST 2018
     */
    private Integer boardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jira_sprint.sprint_id_in_jira
     *
     * @mbg.generated Sun Mar 11 14:31:36 CST 2018
     */
    private Integer sprintIdInJira;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jira_sprint.name
     *
     * @mbg.generated Sun Mar 11 14:31:36 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jira_sprint.jira_id
     *
     * @mbg.generated Sun Mar 11 14:31:36 CST 2018
     */
    private Integer jiraId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jira_sprint.board_id
     *
     * @return the value of jira_sprint.board_id
     *
     * @mbg.generated Sun Mar 11 14:31:36 CST 2018
     */
    public Integer getBoardId() {
        return boardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jira_sprint.board_id
     *
     * @param boardId the value for jira_sprint.board_id
     *
     * @mbg.generated Sun Mar 11 14:31:36 CST 2018
     */
    public void setBoardId(Integer boardId) {
        this.boardId = boardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jira_sprint.sprint_id_in_jira
     *
     * @return the value of jira_sprint.sprint_id_in_jira
     *
     * @mbg.generated Sun Mar 11 14:31:36 CST 2018
     */
    public Integer getSprintIdInJira() {
        return sprintIdInJira;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jira_sprint.sprint_id_in_jira
     *
     * @param sprintIdInJira the value for jira_sprint.sprint_id_in_jira
     *
     * @mbg.generated Sun Mar 11 14:31:36 CST 2018
     */
    public void setSprintIdInJira(Integer sprintIdInJira) {
        this.sprintIdInJira = sprintIdInJira;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jira_sprint.name
     *
     * @return the value of jira_sprint.name
     *
     * @mbg.generated Sun Mar 11 14:31:36 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jira_sprint.name
     *
     * @param name the value for jira_sprint.name
     *
     * @mbg.generated Sun Mar 11 14:31:36 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jira_sprint.jira_id
     *
     * @return the value of jira_sprint.jira_id
     *
     * @mbg.generated Sun Mar 11 14:31:36 CST 2018
     */
    public Integer getJiraId() {
        return jiraId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jira_sprint.jira_id
     *
     * @param jiraId the value for jira_sprint.jira_id
     *
     * @mbg.generated Sun Mar 11 14:31:36 CST 2018
     */
    public void setJiraId(Integer jiraId) {
        this.jiraId = jiraId;
    }
}