package com.iamlile.jira.burndown.model;

public class JiraSprintKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jira_sprint.id
     *
     * @mbg.generated Tue Mar 20 20:19:58 CST 2018
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jira_sprint.id
     *
     * @return the value of jira_sprint.id
     *
     * @mbg.generated Tue Mar 20 20:19:58 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jira_sprint.id
     *
     * @param id the value for jira_sprint.id
     *
     * @mbg.generated Tue Mar 20 20:19:58 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }
}