package com.iamlile.jira.burndown.model;

public class JiraSprintdailyDataWithBLOBs extends JiraSprintdailyData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jira_sprintdailydata.worker_log
     *
     * @mbg.generated Sun Mar 11 14:31:36 CST 2018
     */
    private String workerLog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jira_sprintdailydata.issues_changed
     *
     * @mbg.generated Sun Mar 11 14:31:36 CST 2018
     */
    private String issuesChanged;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jira_sprintdailydata.worker_log
     *
     * @return the value of jira_sprintdailydata.worker_log
     *
     * @mbg.generated Sun Mar 11 14:31:36 CST 2018
     */
    public String getWorkerLog() {
        return workerLog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jira_sprintdailydata.worker_log
     *
     * @param workerLog the value for jira_sprintdailydata.worker_log
     *
     * @mbg.generated Sun Mar 11 14:31:36 CST 2018
     */
    public void setWorkerLog(String workerLog) {
        this.workerLog = workerLog == null ? null : workerLog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jira_sprintdailydata.issues_changed
     *
     * @return the value of jira_sprintdailydata.issues_changed
     *
     * @mbg.generated Sun Mar 11 14:31:36 CST 2018
     */
    public String getIssuesChanged() {
        return issuesChanged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jira_sprintdailydata.issues_changed
     *
     * @param issuesChanged the value for jira_sprintdailydata.issues_changed
     *
     * @mbg.generated Sun Mar 11 14:31:36 CST 2018
     */
    public void setIssuesChanged(String issuesChanged) {
        this.issuesChanged = issuesChanged == null ? null : issuesChanged.trim();
    }
}