package com.iamlile.jira.burndown.model;

public class JiraSprint extends JiraSprintKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jira_sprint.board_id
     *
     * @mbg.generated Tue Mar 20 20:19:58 CST 2018
     */
    private Integer boardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jira_sprint.sprint_id_in_jira
     *
     * @mbg.generated Tue Mar 20 20:19:58 CST 2018
     */
    private Integer sprintIdInJira;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jira_sprint.name
     *
     * @mbg.generated Tue Mar 20 20:19:58 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jira_sprint.jira_id
     *
     * @mbg.generated Tue Mar 20 20:19:58 CST 2018
     */
    private Integer jiraId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jira_sprint.start_date
     *
     * @mbg.generated Tue Mar 20 20:19:58 CST 2018
     */
    private String startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jira_sprint.end_date
     *
     * @mbg.generated Tue Mar 20 20:19:58 CST 2018
     */
    private String endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jira_sprint.complete_date
     *
     * @mbg.generated Tue Mar 20 20:19:58 CST 2018
     */
    private String completeDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jira_sprint.board_id
     *
     * @return the value of jira_sprint.board_id
     *
     * @mbg.generated Tue Mar 20 20:19:58 CST 2018
     */
    public Integer getBoardId() {
        return boardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jira_sprint.board_id
     *
     * @param boardId the value for jira_sprint.board_id
     *
     * @mbg.generated Tue Mar 20 20:19:58 CST 2018
     */
    public void setBoardId(Integer boardId) {
        this.boardId = boardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jira_sprint.sprint_id_in_jira
     *
     * @return the value of jira_sprint.sprint_id_in_jira
     *
     * @mbg.generated Tue Mar 20 20:19:58 CST 2018
     */
    public Integer getSprintIdInJira() {
        return sprintIdInJira;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jira_sprint.sprint_id_in_jira
     *
     * @param sprintIdInJira the value for jira_sprint.sprint_id_in_jira
     *
     * @mbg.generated Tue Mar 20 20:19:58 CST 2018
     */
    public void setSprintIdInJira(Integer sprintIdInJira) {
        this.sprintIdInJira = sprintIdInJira;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jira_sprint.name
     *
     * @return the value of jira_sprint.name
     *
     * @mbg.generated Tue Mar 20 20:19:58 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jira_sprint.name
     *
     * @param name the value for jira_sprint.name
     *
     * @mbg.generated Tue Mar 20 20:19:58 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jira_sprint.jira_id
     *
     * @return the value of jira_sprint.jira_id
     *
     * @mbg.generated Tue Mar 20 20:19:58 CST 2018
     */
    public Integer getJiraId() {
        return jiraId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jira_sprint.jira_id
     *
     * @param jiraId the value for jira_sprint.jira_id
     *
     * @mbg.generated Tue Mar 20 20:19:58 CST 2018
     */
    public void setJiraId(Integer jiraId) {
        this.jiraId = jiraId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jira_sprint.start_date
     *
     * @return the value of jira_sprint.start_date
     *
     * @mbg.generated Tue Mar 20 20:19:58 CST 2018
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jira_sprint.start_date
     *
     * @param startDate the value for jira_sprint.start_date
     *
     * @mbg.generated Tue Mar 20 20:19:58 CST 2018
     */
    public void setStartDate(String startDate) {
        this.startDate = startDate == null ? null : startDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jira_sprint.end_date
     *
     * @return the value of jira_sprint.end_date
     *
     * @mbg.generated Tue Mar 20 20:19:58 CST 2018
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jira_sprint.end_date
     *
     * @param endDate the value for jira_sprint.end_date
     *
     * @mbg.generated Tue Mar 20 20:19:58 CST 2018
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate == null ? null : endDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jira_sprint.complete_date
     *
     * @return the value of jira_sprint.complete_date
     *
     * @mbg.generated Tue Mar 20 20:19:58 CST 2018
     */
    public String getCompleteDate() {
        return completeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jira_sprint.complete_date
     *
     * @param completeDate the value for jira_sprint.complete_date
     *
     * @mbg.generated Tue Mar 20 20:19:58 CST 2018
     */
    public void setCompleteDate(String completeDate) {
        this.completeDate = completeDate == null ? null : completeDate.trim();
    }
}