package org.mapper;

import com.iamlile.jira.burndown.model.Jira;
import com.iamlile.jira.burndown.model.JiraKey;
import com.iamlile.jira.burndown.model.JiraWithBLOBs;
import org.apache.ibatis.annotations.*;

@Mapper
public interface JiraMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jira
     *
     * @mbg.generated Sat Feb 17 17:35:16 CST 2018
     */
    @Delete({
        "delete from jira",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(JiraKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jira
     *
     * @mbg.generated Sat Feb 17 17:35:16 CST 2018
     */
    @Insert({
        "insert into jira (id, name, ",
        "url, username, password, ",
        "task_percent_id, board_watch)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{url,jdbcType=VARCHAR}, #{username,jdbcType=VARCHAR}, #{password,jdbcType=VARCHAR}, ",
        "#{taskPercentId,jdbcType=VARCHAR}, #{boardWatch,jdbcType=LONGVARCHAR})"
    })
    int insert(JiraWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jira
     *
     * @mbg.generated Sat Feb 17 17:35:16 CST 2018
     */
    int insertSelective(JiraWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jira
     *
     * @mbg.generated Sat Feb 17 17:35:16 CST 2018
     */
    @Select({
        "select",
        "id, name, url, username, password, task_percent_id, board_watch",
        "from jira",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.iamlile.jira.burndown.mapper.JiraMapper.ResultMapWithBLOBs")
    JiraWithBLOBs selectByPrimaryKey(JiraKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jira
     *
     * @mbg.generated Sat Feb 17 17:35:16 CST 2018
     */
    int updateByPrimaryKeySelective(JiraWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jira
     *
     * @mbg.generated Sat Feb 17 17:35:16 CST 2018
     */
    @Update({
        "update jira",
        "set name = #{name,jdbcType=VARCHAR},",
          "url = #{url,jdbcType=VARCHAR},",
          "username = #{username,jdbcType=VARCHAR},",
          "password = #{password,jdbcType=VARCHAR},",
          "task_percent_id = #{taskPercentId,jdbcType=VARCHAR},",
          "board_watch = #{boardWatch,jdbcType=LONGVARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKeyWithBLOBs(JiraWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jira
     *
     * @mbg.generated Sat Feb 17 17:35:16 CST 2018
     */
    @Update({
        "update jira",
        "set name = #{name,jdbcType=VARCHAR},",
          "url = #{url,jdbcType=VARCHAR},",
          "username = #{username,jdbcType=VARCHAR},",
          "password = #{password,jdbcType=VARCHAR},",
          "task_percent_id = #{taskPercentId,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Jira record);
}