package com.iamlile.jira.burndown.mapper;

import com.iamlile.jira.burndown.model.JiraSprintdailyData;
import com.iamlile.jira.burndown.model.JiraSprintdailyDataKey;
import com.iamlile.jira.burndown.model.JiraSprintdailyDataWithBLOBs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface JiraSprintdailyDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jira_sprintdailydata
     *
     * @mbg.generated Sun Mar 11 13:57:37 CST 2018
     */
    @Delete({
        "delete from jira_sprintdailydata",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(JiraSprintdailyDataKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jira_sprintdailydata
     *
     * @mbg.generated Sun Mar 11 13:57:37 CST 2018
     */
    @Insert({
        "insert into jira_sprintdailydata (id, date, remaining_work_hours, ",
        "completed_work_hours, sprint_id, ",
        "worker_log, issues_changed)",
        "values (#{id,jdbcType=INTEGER}, #{date,jdbcType=DATE}, #{remainingWorkHours,jdbcType=DOUBLE}, ",
        "#{completedWorkHours,jdbcType=DOUBLE}, #{sprintId,jdbcType=INTEGER}, ",
        "#{workerLog,jdbcType=LONGVARCHAR}, #{issuesChanged,jdbcType=LONGVARCHAR})"
    })
    int insert(JiraSprintdailyDataWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jira_sprintdailydata
     *
     * @mbg.generated Sun Mar 11 13:57:37 CST 2018
     */
    int insertSelective(JiraSprintdailyDataWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jira_sprintdailydata
     *
     * @mbg.generated Sun Mar 11 13:57:37 CST 2018
     */
    @Select({
        "select",
        "id, date, remaining_work_hours, completed_work_hours, sprint_id, worker_log, ",
        "issues_changed",
        "from jira_sprintdailydata",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.iamlile.jira.burndown.mapper.JiraSprintdailyDataMapper.ResultMapWithBLOBs")
    JiraSprintdailyDataWithBLOBs selectByPrimaryKey(JiraSprintdailyDataKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jira_sprintdailydata
     *
     * @mbg.generated Sun Mar 11 13:57:37 CST 2018
     */
    int updateByPrimaryKeySelective(JiraSprintdailyDataWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jira_sprintdailydata
     *
     * @mbg.generated Sun Mar 11 13:57:37 CST 2018
     */
    @Update({
        "update jira_sprintdailydata",
        "set date = #{date,jdbcType=DATE},",
          "remaining_work_hours = #{remainingWorkHours,jdbcType=DOUBLE},",
          "completed_work_hours = #{completedWorkHours,jdbcType=DOUBLE},",
          "sprint_id = #{sprintId,jdbcType=INTEGER},",
          "worker_log = #{workerLog,jdbcType=LONGVARCHAR},",
          "issues_changed = #{issuesChanged,jdbcType=LONGVARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKeyWithBLOBs(JiraSprintdailyDataWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jira_sprintdailydata
     *
     * @mbg.generated Sun Mar 11 13:57:37 CST 2018
     */
    @Update({
        "update jira_sprintdailydata",
        "set date = #{date,jdbcType=DATE},",
          "remaining_work_hours = #{remainingWorkHours,jdbcType=DOUBLE},",
          "completed_work_hours = #{completedWorkHours,jdbcType=DOUBLE},",
          "sprint_id = #{sprintId,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(JiraSprintdailyData record);
}